# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rClickrmacOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rClickrmacOS
  pod 'FirebaseCommunity'
  pod 'FirebaseCommunity/Database'
  pod 'FirebaseCommunity/Storage'

end
